### ISSUE TITLE
 MPU6050_9Axis_MotionApps41.h

### ISSUE THREAD

**Issue by choolake** [jrowberg/i2cdevlib#18]
In the MPU6050_6Axis_MotionApps20.h cause the quaternion to initialized in the power up direction. In other words the axis system of the wold frame depends on the power up orientation of the sensor. This is because that it does not have a magnetometer it cant make a fixed axis system. But with MPU6050_9Axis_MotionApps41.h this issue need to be solved since it uses the magnetometer but it does not use the magnetometer reading to correct the 6 -axis quaternion given by the MPU 6050. can you describe a way to correct the quaternion that is given by the MPU to not to depend on the power up direction but to depend on the magnetometer magmatic north. 
thank you!

**Comment by guyl44** [comment]
Hey, I was wondering - is there a working version of MPU6050_9Axis_MotionApps41.h that communicates with the HMC5883L? Even a semi-working version? Anything?

I realize this is an old thread/issue, but I thought I might as well give it a shot.

**Comment by paddywwoof** [comment]
I don't know how active this corner of this (very excellent) project is, but for what it's worth this is what I did and it might be a way to put 9Axis functionality into the library.

In the example MPU6050_DMP6.ino (line numbers approx because of non-relevant additions) I've copied the hmc5883l bits straight from the examples with that library (scale and measurement mode) and don't know if they're optimal. See also my comment about it settling in a slightly arbitrary direction.

The essential functionality, after including the hmc5883l and setI2CBypassEnabled(true) is to rotate the compass vector by the dmp orientation quaternion then subtract the heading result from the yaw. (I assumed to start that I would need the inverse rotation but that didn't work) There is more noise in the magnetometer readings than the dmp and the rate of drift is slow so it would probably be a good idea to apply a smoothing to the correction factor.

```
43c44
< 
---
> #include <hmc5883l.h>
63a66,67
> hmc5883l compass;
> 
236a241,244
>     mpu.setI2CBypassEnabled(true);
>     compass = hmc5883l();
>     compass.SetScale(1.3); // Set the scale of the compass.
>     compass.SetMeasurementMode(Measurement_Continuous); // Set the measurement mode to Continuous
317a335,344
>             MagnetometerScaled mags = compass.ReadScaledAxis();
>             VectorFloat compass_vector = VectorFloat(mags.XAxis, mags.YAxis, mags.ZAxis);
>             /* includes the slipping Yaw value which can be cancelled by subtracting this 
>              *  compensated compass direction from the yaw figure. However it still includes
>              *  an arbitrary starting point. TODO during the arming warmup phase, while the
>              *  gyro is horizontal set a constant to make the yaw figure match the settled
>              *  compass direction.
>             */
>             compass_vector.rotate(&q);
>             ypr[0] -= atan2f(compass_vector.y, compass_vector.z);
```

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
