### ISSUE TITLE
How to get relative rotation matrix from two consecutive orientations of MPU6050

### ISSUE THREAD

**Issue by shomedas** [jrowberg/i2cdevlib#429]
I need to find the relative rotation matrix between two orientations of MPU6050. My approach (which fails) uses the MPU6050 quaternion (from output readable quaternion ). Let quaternion at orientation 1 be q1 & quaternion at orientation 2 be q2.

I find the relative qualternion q =q2*q1_inverse. Then I convert the relative quaternion to a rotation matrix and also a axis-angle representation.

However on examining the rotation matrix & the axis vector, I find that they are highly incorrect.

Kindly suggest how I can get the rotation matrix from the MPU6050. Or do I need to use the MPU9250?

**Comment by jrowberg** [comment]
This is an interesting quaternion math problem, but it should really go in the [I2Cdevlib forums](https://www.i2cdevlib.com/forums/) or even something more specific like [Stack Exchange for Mathematics](https://math.stackexchange.com/). Since it doesn't concern the underlying library code, I'll close the issue here.
