### ISSUE TITLE
how to connect two mpu6050 to arduino uno

### ISSUE THREAD

**Issue by reut10** [jrowberg/i2cdevlib#63]
Hi!
I want to connect my arduino uno to two mpu 6050 in order to learn about the relative angles and velocity,
there is some ready program for this?
how to connect the 2 mpu 6050 ?
thank you,
reut :)

**Comment by Tirocinio** [comment]
Hello everybody,
We should connect two mpu6050 to an Arduino mega but we don't know how to connect them physically.
We know that we have to turn the i2c adress from 0x68 to 0x69 in order to have 2 different adress, one for each sensor.
Someone says that it must connect them in parallel but other thinks that it is usefull to set two digital pins high or low to "swich on/off" a sensor in order to read information alternated.
moreover we would like to read quarternion or euler data but now we are only able to receive raw data.
May anyone help us?
thanks

**Comment by jorgediosdado** [comment]
Hi,
I am also trying to read values from two MPU6050. I just started looking into this, and for what I've read, raw values can be read from both devices. 

My question is, is it possible to read values computed by DMP for two MPU6050? 

Thanks!

**Comment by eadf** [comment]
Yes, it is possible to connect more than one MPU6050 to an Arduino. I'm currently testing an extended example of MPU6050_DMP.ino that can connect to any number of accelerometers. The only limit is the number of interrupt pins. 

I'll upload a temporary repository here: https://github.com/eadf/MPU6050_DMP6_Multiple

**Comment by jorgediosdado** [comment]
Cool,
It looks really good. What is the correct hardware setup? Do I need to do something in order to change I2C addresses? Any idea of what frequency can I get working with two IMUs?
I am relatively new to I2C and this sensor, so any help is appreciated!

**Comment by eadf** [comment]
With the MPU6050_DMP6_Multiple example you will always use the `MPU6050_ADDRESS_AD0_HIGH` address to talk to the MPU6050s. The wrapper code in the example will set the AD0 high on the device it wants to talk to (all the others will have AD0 low)

At 100Hz FIFO a 8Mhz pro mini is just about able to printout pitch and roll of two devices. So I use to lower the FIFO frequency with `MPU6050_DMP_FIFO_RATE_DIVISOR` (a feature only found in the develop branch of i2cdevlib). 

I have not tested the max speed yet. But I imagine a Due or esp8266 should be able to handle quite high FIFO rates.

Regarding the wiring.. you just setup the devices with the i2c pins in parallel as usual. AD0 and INT needs to be connected to separate Arduino pins. Look at the README.md

**Comment by jorgediosdado** [comment]
I succesfully read values from the two imus (pitch and roll). Everything is good for some time and then it stops. Any suggestion?

**Comment by eadf** [comment]
`MPU6050_DMP_FIFO_RATE_DIVISOR` could be set too low relative to your CPU speed and Serial transmission speed (it's set in MPU6050_Wrapper.h) 

Remove all frequent and unnecessary Serial.print():s. In the demo I printout the measured FIFO speed in Hz for each sample. Remove that.

In `MPU6050_Array::select(uint8_t device)` there is a `delay(1)` that I commented out for some reason..
Maybe the IMUs needs some time after AD0 is switched. Try to re-add that delay and try different delay values.

**Comment by eadf** [comment]
Hm, I just tested with `delay(1)` and `MPU6050_DMP_FIFO_RATE_DIVISOR=3` it ran for some 30 minutes on a Pro Mini 8MHz, then it stopped. I'll have to investigate this some more.

**Comment by jorgediosdado** [comment]
I am also changing delay time and ` MPU6050_DMP_FIFO_RATE_DIVISOR` time, but no luck on getting it to work for more than half a minute or so.

**Comment by eadf** [comment]
Are you using the develop branch of i2cdevlib? 

Let's move the discussion to the [MPU6050_DMP6_Multiple](https://github.com/eadf/MPU6050_DMP6_Multiple) repository. Open an issue there and we'll try to figure this out.

**Comment by felipeLvalero** [comment]
@jorgediosdado Hi, I'm pretty new in this arduino World, 
I'm reading your code and can see how you read the accelerometer but, how to read the Gyro in the two MPUs? 

thanks in advance.

**Comment by jwaluyo** [comment]
@loowiz Hi, I'm beginner in this thing can you help me please. i've tried to modification I2C code you sent up and put the libraries on the same directory of sketch but still have trouble when i compiled

**Comment by jwaluyo** [comment]
@reut10 can you help me for my trouble please? i'm confusing with the code.
hows the code looks like?

**Comment by jwaluyo** [comment]
@reut10 can you help me for my trouble please? i'm confusing with the code, so many errors in my sketch that i can't understand...

**Comment by Haro193** [comment]
Hi,
I want to connect my arduino mega to three or more mpu 6050, there is some ready program for this?
how to connect the 3 or more mpu 6050?

thank you,
LucasHaro.

**Comment by piroozn** [comment]
You can connect two MPU6050 on the I2C buss without any additional circuit.
If you want more than 2 then you have to use a GPIO to control each MPU6050 AD) and selectively set it to 1 on the MPU6050 that you want selected and address that device with LSB set to 1. Please refer to its data sheet and simply select the device you want by setting GPIO to 1 on the selected device and that would be enable on the I2C when your address LSB is 1.
Your control processor most likely needs to be higher performance to be able to handle such configuration since you are going to get lots of data. You may want to switch to a higher performance Arduino to be able to successfully use it in this configuration. Multiple core may be suitable for this configuration.

**Comment by Werther86** [comment]
Hi there, firstly that's a nice job; it works flawless on Arduino UNO.

But I am trying to make it work on Arduino DUE and it doesn't compile with the error below:
"exit status 1
'_BV' was not declared in this scope"
at the line:
"if (currentMPU->_mpuIntStatus & _BV(MPU6050_INTERRUPT_DMP_INT_BIT)) {"

The code is mainly the same therefore don't see pasting it here is necessary; but I can if you wish.

I tried to find out the cause of the problem by myself on forums and the internet but didn't encounter any solid output. Only thoese with the LCD libraries etc.

Anyone has any idea? _BV seems to be covered in I2Clib and not in wrapper or even in MPU libraries itself. So any suggestion is appreciated.

Additional INFO:
Using GY521 of MPU6050
Arduino IDE is 1.6.10
On DUE, "new IDE" sticker exists, board info:
BN: Arduino Due (Programming Port)
VID: 2A03
PID: 003D

**Comment by hamiderza** [comment]
hi, i want to connect three MPU6050 with and an arduino mega or uno. i know that using multiplexer such as 74hct4067 is an solution for it, is there some ready program to run it? can you help me about circuit and connecting two MPU6050 with each others ?

**Comment by ridwankabir** [comment]
I think I might have figured a way to use **Jeff Rowberg's** example of using **DMP** in two **MPU6050s**.

I am using an **Arduino NANO** and for the record it has **INTERRUPTS** attached to two pins Digital I/O pins **2** and **3** and has on board 5V and 3.3V power supply. 

I've used **pin 2** for **MPU(0x68)** with **AD0** set to **LOW** and **pin 3** for **MPU(0x69)** with **AD0** set to **HIGH**. I also connected a **2.2k** pull-up resistors with each **SCL** and **SDA** on the **MPU(0x69)**.

I repeated the same code for each of the MPUs with separate variables.

**I found out that supplying Arduino's 5V to AD0 on MPU(0x69) caused the program to stop writing on the serial monitor after a while**. But as soon as I connected **AD0** to **3.3V** on the Arduino............. voila!!!! problem gone. I have been successful in collecting data from both the MPUs and also a flex sensor for over an hour now without any problem.

I hope this helps. Thank you.  

Ridwan Kabir

**Comment by ridwankabir** [comment]
Hi Ian Lowe,

Have you specified any address for the led? Like 0x3f or 0x27 ? You may check this link for details on led connection and stuff

https://github.com/zegreatclan/AssettoCorsaTools/wiki/Arduino-20x4-I2C-LCD

As the SDA and SCL lines are common the devices must have separate addresses. For example , two mpu 6050s need to have addresses 0x68( AD0 pin set to GND ) and 0x69 (AD0 pin set to 3.3 v) for them communicate via i2c simultaneously and also separate interrupt lines are required. Make sure not to apply 5v on VCC of  the MPU with address 0x69 as it has already been powered by 3.3 v on the AD0 pin.
At first, I used the pullup resistors on the second MPU but then I removed them. It works just fine in both cases. 
I have not tried using one MPU as a slave to the other. So I am not sure about tha XDA,XCL  connection part.

**Comment by Maruthi-97** [comment]
Hai everyone
I am trying to use 5 mpu6050 units and the task is all should be read simultaneously. Have anyone used like this earlier? I have used two units with Arduino Mega 2560.
 Please suggest me the best board to drive all units along with Kalman code.

**Comment by franclab1887** [comment]
Hello everyone,
I am currently trying to use two MPU6050 on a Arduino UNO and I have the overflow issue like most of the people. 
You can find my code down below, it only work for some values and the rest are just overflow or 0   0   90 degrees that can't be right. 
@ridwankabir I tried to double everything as you said and yet it doesn't work if you can help me please?
for the connections the gyro one :   Vcc==>5v, gnd==>gnd, SCL==> A5, SCA ==> A4, AD0==> GND  and INT to pin2 the second gyro:  gnd==>gnd, SCL==> A5, SCA ==> A4 and AD0==> GND.  int to pin 3.

#include <I2Cdev.h>

#include <MPU6050_6Axis_MotionApps20.h>
#include "MPU6050.h" // not necessary if using MotionApps include file

// Arduino Wire library is required if I2Cdev I2CDEV_ARDUINO_WIRE implementation
// is used in I2Cdev.h
#if I2CDEV_IMPLEMENTATION == I2CDEV_ARDUINO_WIRE
    #include <Wire.h>
#endif

// class default I2C address is 0x68
// specific I2C addresses may be passed as a parameter here
//AD0 low = 0x68 (default for SparkFun breakout and InvenSense evaluation board)
//AD0 high = 0x69
MPU6050 mpu=0x68;
MPU6050 mpu1= 0x69; // <-- use for AD0 high

/* =========================================================================
   NOTE: In addition to connection 3.3v, GND, SDA, and SCL, this sketch
   depends on the MPU-6050's INT pin being connected to the Arduino's
   external interrupt #0 pin. On the Arduino Uno and Mega 2560, this is
   digital I/O pin 2.
 * ========================================================================= */

/* =========================================================================
   NOTE: Arduino v1.0.1 with the Leonardo board generates a compile error
   when using Serial.write(buf, len). The Teapot output uses this method.
   The solution requires a modification to the Arduino USBAPI.h file, which
   is fortunately simple, but annoying. This will be fixed in the next IDE
   release. For more info, see these links:

   http://arduino.cc/forum/index.php/topic,109987.0.html
   http://code.google.com/p/arduino/issues/detail?id=958
 * ========================================================================= */



// uncomment "OUTPUT_READABLE_QUATERNION" if you want to see the actual
// quaternion components in a [w, x, y, z] format (not best for parsing
// on a remote host such as Processing or something though)
//#define OUTPUT_READABLE_QUATERNION

// uncomment "OUTPUT_READABLE_EULER" if you want to see Euler angles
// (in degrees) calculated from the quaternions coming from the FIFO.
// Note that Euler angles suffer from gimbal lock (for more info, see
// http://en.wikipedia.org/wiki/Gimbal_lock)
//#define OUTPUT_READABLE_EULER

// uncomment "OUTPUT_READABLE_YAWPITCHROLL" if you want to see the yaw/
// pitch/roll angles (in degrees) calculated from the quaternions coming
// from the FIFO. Note this also requires gravity vector calculations.
// Also note that yaw/pitch/roll angles suffer from gimbal lock (for
// more info, see: http://en.wikipedia.org/wiki/Gimbal_lock)
#define OUTPUT_READABLE_YAWPITCHROLL
#define OUTPUT_READABLE_YAWPITCHROLL1
// uncomment "OUTPUT_READABLE_REALACCEL" if you want to see acceleration
// components with gravity removed. This acceleration reference frame is
// not compensated for orientation, so +X is always +X according to the
// sensor, just without the effects of gravity. If you want acceleration
// compensated for orientation, us OUTPUT_READABLE_WORLDACCEL instead.
//#define OUTPUT_READABLE_REALACCEL

// uncomment "OUTPUT_READABLE_WORLDACCEL" if you want to see acceleration
// components with gravity removed and adjusted for the world frame of
// reference (yaw is relative to initial orientation, since no magnetometer
// is present in this case). Could be quite handy in some cases.
//#define OUTPUT_READABLE_WORLDACCEL

// uncomment "OUTPUT_TEAPOT" if you want output that matches the
// format used for the InvenSense teapot demo
//#define OUTPUT_TEAPOT



#define INTERRUPT_PIN 2  // use pin 2 on Arduino Uno & most boards
#define LED_PIN 13 // (Arduino is 13, Teensy is 11, Teensy++ is 6)
bool blinkState = false;

// MPU control/status vars
bool dmpReady = false;  // set true if DMP init was successful
uint8_t mpuIntStatus;   // holds actual interrupt status byte from MPU
uint8_t devStatus;      // return status after each device operation (0 = success, !0 = error)
uint16_t packetSize;    // expected DMP packet size (default is 42 bytes)
uint16_t fifoCount;     // count of all bytes currently in FIFO
uint8_t fifoBuffer[64]; // FIFO storage buffer

// orientation/motion vars
Quaternion q;           // [w, x, y, z]         quaternion container
VectorInt16 aa;         // [x, y, z]            accel sensor measurements
VectorInt16 aaReal;     // [x, y, z]            gravity-free accel sensor measurements
VectorInt16 aaWorld;    // [x, y, z]            world-frame accel sensor measurements
VectorFloat gravity;    // [x, y, z]            gravity vector
float euler[3];         // [psi, theta, phi]    Euler angle container
float ypr[3];           // [yaw, pitch, roll]   yaw/pitch/roll container and gravity vector

// packet structure for InvenSense teapot demo
uint8_t teapotPacket[14] = { '$', 0x02, 0,0, 0,0, 0,0, 0,0, 0x00, 0x00, '\r', '\n' };

// MPU control/status vars 1
bool dmp1Ready = false;  // set true if DMP init was successful
uint8_t mpu1IntStatus;   // holds actual interrupt status byte from MPU
uint8_t devStatus1;      // return status after each device operation (0 = success, !0 = error)
uint16_t packetSize1;    // expected DMP packet size (default is 42 bytes)
uint16_t fifoCount1;     // count of all bytes currently in FIFO
uint8_t fifoBuffer1[64]; // FIFO storage buffer

// orientation/motion vars
Quaternion q1;           // [w, x, y, z]         quaternion container
VectorInt16 aa1;         // [x, y, z]            accel sensor measurements
VectorInt16 aaReal1;     // [x, y, z]            gravity-free accel sensor measurements
VectorInt16 aaWorld1;    // [x, y, z]            world-frame accel sensor measurements
VectorFloat gravity1;    // [x, y, z]            gravity vector
float euler1[3];         // [psi, theta, phi]    Euler angle container
float ypr1[3];           // [yaw, pitch, roll]   yaw/pitch/roll container and gravity vector

// packet structure for InvenSense teapot demo
uint8_t teapotPacket1[14] = { '$', 0x02, 0,0, 0,0, 0,0, 0,0, 0x00, 0x00, '\r', '\n' };


// ================================================================
// ===               INTERRUPT DETECTION ROUTINE                ===
// ================================================================

volatile bool mpuInterrupt = false;     // indicates whether MPU interrupt pin has gone high
volatile bool mpu1Interrupt = false;
void dmpDataReady() {
    mpuInterrupt = true;
}

int rawnumber=0; //number in the table printing
// ================================================================
// ===               INTERRUPT DETECTION ROUTINE 1                ===
// ================================================================

void dmp1DataReady() {
    mpu1Interrupt = true;
}

int rawnumber1=0; //number in the table printing

// ================================================================
// ===                      INITIAL SETUP                       ===
// ================================================================

void setup() {
    // join I2C bus (I2Cdev library doesn't do this automatically)
    #if I2CDEV_IMPLEMENTATION == I2CDEV_ARDUINO_WIRE
        Wire.begin();
        Wire.setClock(400000); // 400kHz I2C clock. Comment this line if having compilation difficulties
    #elif I2CDEV_IMPLEMENTATION == I2CDEV_BUILTIN_FASTWIRE
        Fastwire::setup(400, true);
    #endif

    // initialize serial communication
    // (115200 chosen because it is required for Teapot Demo output, but it's
    // really up to you depending on your project)
    Serial.begin(115200);
    while (!Serial); // wait for Leonardo enumeration, others continue immediately

    // NOTE: 8MHz or slower host processors, like the Teensy @ 3.3v or Ardunio
    // Pro Mini running at 3.3v, cannot handle this baud rate reliably due to
    // the baud timing being too misaligned with processor ticks. You must use
    // 38400 or slower in these cases, or use some kind of external separate
    // crystal solution for the UART timer.

    // initialize device
    Serial.println(F("Initializing I2C devices..."));
    mpu.initialize();
    mpu1.initialize();
    pinMode(INTERRUPT_PIN, INPUT);
    pinMode(3,INPUT);
    // verify connection
    Serial.println(F("Testing device connections..."));
    Serial.println(mpu.testConnection() ? F("MPU6050 connection successful") : F("MPU6050 connection failed"));
    Serial.println(mpu1.testConnection() ? F("MPU6050(1) connection successful") : F("MPU6050(1) connection failed")); 
    
    // wait for ready
    //Serial.println(F("\nSend any character to begin DMP programming and demo: "));
   // while (Serial.available() && Serial.read()); // empty buffer
    //while (!Serial.available());                 // wait for data
    //while (Serial.available() && Serial.read()); // empty buffer again
   
    Serial.println("wait for the values to stabilize after the initialization, it may take a few seconds");
    // load and configure the DMP
    Serial.println(F("Initializing DMP..."));
    devStatus = mpu.dmpInitialize();
    devStatus1 = mpu1.dmpInitialize();
    // supply your own gyro offsets here, scaled for min sensitivity
    mpu.setXGyroOffset(25);
    mpu.setYGyroOffset(-6);
    mpu.setZGyroOffset(43);
    mpu.setZAccelOffset(1187); // 1688 factory default for my test chip

    mpu1.setXGyroOffset(25);
    mpu1.setYGyroOffset(-6);
    mpu1.setZGyroOffset(43);
    mpu1.setZAccelOffset(1187); // 1688 factory default for my test chip

    // make sure it worked (returns 0 if so)
    if (devStatus == 0) {
        // turn on the DMP, now that it's ready
        Serial.println(F("Enabling DMP..."));
        mpu.setDMPEnabled(true);

        // enable Arduino interrupt detection
        Serial.println(F("Enabling interrupt detection (Arduino external interrupt 0)..."));
        attachInterrupt(digitalPinToInterrupt(INTERRUPT_PIN), dmpDataReady, RISING);
        mpuIntStatus = mpu.getIntStatus();

        // set our DMP Ready flag so the main loop() function knows it's okay to use it
        Serial.println(F("DMP ready! Waiting for first interrupt..."));
        dmpReady = true;

// make sure it worked (returns 0 if so)
    if (devStatus1 == 0) {
        // turn on the DMP, now that it's ready
        Serial.println(F("Enabling DMP1..."));
        mpu1.setDMPEnabled(true);

        // enable Arduino interrupt detection
        Serial.println(F("Enabling interrupt detection1 (Arduino external interrupt 0)..."));
        attachInterrupt(digitalPinToInterrupt(3), dmp1DataReady, RISING);
        mpu1IntStatus = mpu1.getIntStatus();

        // set our DMP Ready flag so the main loop() function knows it's okay to use it
        Serial.println(F("DMP ready! Waiting for first interrupt1..."));
        dmp1Ready = true;

        // get expected DMP packet size for later comparison
        packetSize = mpu.dmpGetFIFOPacketSize();

        packetSize1 = mpu1.dmpGetFIFOPacketSize();
    } 
    else {
        // ERROR!
        // 1 = initial memory load failed
        // 2 = DMP configuration updates failed
        // (if it's going to break, usually the code will be 1)
        Serial.print(F("DMP Initialization failed (code "));
        Serial.print(devStatus);
        Serial.print(devStatus1);
        Serial.println(F(")"));
    }

    // configure LED for output
    pinMode(LED_PIN, OUTPUT);
}
}


// ================================================================
// ===                    MAIN PROGRAM LOOP                     ===
// ================================================================

void loop() {
    // if programming failed, don't try to do anything
    if (!dmpReady) return;
    if (!dmp1Ready) return;
    // wait for MPU interrupt or extra packet(s) available
    
    

    // reset interrupt flag and get INT_STATUS byte
    mpuInterrupt = false;
    mpuIntStatus = mpu.getIntStatus();
    
    mpu1Interrupt = false;
    mpu1IntStatus = mpu1.getIntStatus();
    
    // get current FIFO count
    fifoCount = mpu.getFIFOCount();
    fifoCount1 = mpu1.getFIFOCount();
    
    // check for overflow (this should never happen unless our code is too inefficient)
    if ((mpuIntStatus & 0x10) || fifoCount == 1024) {
        // reset so we can continue cleanly
        mpu.resetFIFO();
        Serial.println(F("FIFO overflow!"));
    if ((mpu1IntStatus & 0x10) || fifoCount1 == 1024) {
        // reset so we can continue cleanly
        mpu1.resetFIFO();
        Serial.println(F("FIFO1 overflow!"));
        
    // otherwise, check for DMP data ready interrupt (this should happen frequently)
    } 
     if (mpuIntStatus & 0x02) {
        // wait for correct available data length, should be a VERY short wait
        while (fifoCount < packetSize) fifoCount = mpu.getFIFOCount();

        // read a packet from FIFO
        mpu.getFIFOBytes(fifoBuffer, packetSize);
        
        // track FIFO count here in case there is > 1 packet available
        // (this lets us immediately read more without waiting for an interrupt)
        fifoCount -= packetSize;

        #ifdef OUTPUT_READABLE_QUATERNION
            // display quaternion values in easy matrix form: w x y z
            mpu.dmpGetQuaternion(&q, fifoBuffer);
            Serial.print("quat\t");
            Serial.print(q.w);
            Serial.print("\t");
            Serial.print(q.x);
            Serial.print("\t");
            Serial.print(q.y);
            Serial.print("\t");
            Serial.println(q.z);
        #endif

        #ifdef OUTPUT_READABLE_EULER
            // display Euler angles in degrees
            mpu.dmpGetQuaternion(&q, fifoBuffer);
            mpu.dmpGetEuler(euler, &q);
            Serial.print("euler\t");
            Serial.print(euler[0] * 180/M_PI);
            Serial.print("\t");
            Serial.print(euler[1] * 180/M_PI);
            Serial.print("\t");
            Serial.println(euler[2] * 180/M_PI);
        #endif

        #ifdef OUTPUT_READABLE_YAWPITCHROLL
            // display Euler angles in degrees
            mpu.dmpGetQuaternion(&q, fifoBuffer);
            mpu.dmpGetGravity(&gravity, &q);
            mpu.dmpGetYawPitchRoll(ypr, &q, &gravity);
            
            rawnumber++;
            Serial.print(rawnumber);
            Serial.print('\t');
            Serial.print(ypr[0] * 180/M_PI);
            Serial.print('\t');
            Serial.print(ypr[1] * 180/M_PI);
            Serial.print('\t');
            Serial.print(ypr[2] * 180/M_PI);
            Serial.print('\t');
        #endif

        #ifdef OUTPUT_READABLE_REALACCEL
            // display real acceleration, adjusted to remove gravity
            mpu.dmpGetQuaternion(&q, fifoBuffer);
            mpu.dmpGetAccel(&aa, fifoBuffer);
            mpu.dmpGetGravity(&gravity, &q);
            mpu.dmpGetLinearAccel(&aaReal, &aa, &gravity);
            Serial.print("areal\t");
            Serial.print(aaReal.x);
            Serial.print("\t");
            Serial.print(aaReal.y);
            Serial.print("\t");
            Serial.println(aaReal.z);
        #endif

        #ifdef OUTPUT_READABLE_WORLDACCEL
            // display initial world-frame acceleration, adjusted to remove gravity
            // and rotated based on known orientation from quaternion
            mpu.dmpGetQuaternion(&q, fifoBuffer);
            mpu.dmpGetAccel(&aa, fifoBuffer);
            mpu.dmpGetGravity(&gravity, &q);
            mpu.dmpGetLinearAccel(&aaReal, &aa, &gravity);
            mpu.dmpGetLinearAccelInWorld(&aaWorld, &aaReal, &q);
            Serial.print("aworld\t");
            Serial.print(aaWorld.x);
            Serial.print("\t");
            Serial.print(aaWorld.y);
            Serial.print("\t");
            Serial.println(aaWorld.z);
        #endif
    
        #ifdef OUTPUT_TEAPOT
            // display quaternion values in InvenSense Teapot demo format:
            teapotPacket[2] = fifoBuffer[0];
            teapotPacket[3] = fifoBuffer[1];
            teapotPacket[4] = fifoBuffer[4];
            teapotPacket[5] = fifoBuffer[5];
            teapotPacket[6] = fifoBuffer[8];
            teapotPacket[7] = fifoBuffer[9];
            teapotPacket[8] = fifoBuffer[12];
            teapotPacket[9] = fifoBuffer[13];
            Serial.write(teapotPacket, 14);
            teapotPacket[11]++; // packetCount, loops at 0xFF on purpose
        #endif

        // blink LED to indicate activity
        blinkState = !blinkState;
        digitalWrite(LED_PIN, blinkState);
    }
     if (mpu1IntStatus & 0x02) {
        // wait for correct available data length, should be a VERY short wait
        while (fifoCount1 < packetSize1) fifoCount1 = mpu1.getFIFOCount();

        // read a packet from FIFO
        mpu1.getFIFOBytes(fifoBuffer1, packetSize1);
        
        // track FIFO count here in case there is > 1 packet available
        // (this lets us immediately read more without waiting for an interrupt)
        fifoCount1 -= packetSize1;

        #ifdef OUTPUT_READABLE_QUATERNION1
            // display quaternion values in easy matrix form: w x y z
            mpu1.dmpGetQuaternion(&q1, fifoBuffer1);
            Serial.print("quat\t");
            Serial.print(q1.w);
            Serial.print("\t");
            Serial.print(q1.x);
            Serial.print("\t");
            Serial.print(q1.y);
            Serial.print("\t");
            Serial.println(q1.z);
        #endif

        #ifdef OUTPUT_READABLE_EULER1
            // display Euler angles in degrees
            mpu1.dmpGetQuaternion(&q1, fifoBuffer1);
            mpu1.dmpGetEuler(euler1, &q1);
            Serial.print("euler\t");
            Serial.print(euler1[0] * 180/M_PI);
            Serial.print("\t");
            Serial.print(euler1[1] * 180/M_PI);
            Serial.print("\t");
            Serial.println(euler1[2] * 180/M_PI);
        #endif

        #ifdef OUTPUT_READABLE_YAWPITCHROLL1
            // display Euler angles in degrees
            mpu1.dmpGetQuaternion(&q1, fifoBuffer1);
            mpu1.dmpGetGravity(&gravity1, &q1);
            mpu1.dmpGetYawPitchRoll(ypr1, &q1, &gravity1);
            
            rawnumber1++;
            Serial.print(rawnumber1);
            Serial.print('\t');
            Serial.print(ypr1[0] * 180/M_PI);
            Serial.print('\t');
            Serial.print(ypr1[1] * 180/M_PI);
            Serial.print('\t');
            Serial.print(ypr1[2] * 180/M_PI);
             Serial.println('\t');
        #endif

        #ifdef OUTPUT_READABLE_REALACCEL1
            // display real acceleration, adjusted to remove gravity
            mpu1.dmpGetQuaternion(&q1, fifoBuffer1);
            mpu1.dmpGetAccel(&aa1, fifoBuffer1);
            mpu1.dmpGetGravity(&gravity1, &q1);
            mpu1.dmpGetLinearAccel(&aaReal1, &aa1, &gravity1);
            Serial.print("areal1\t");
            Serial.print(aaReal1.x);
            Serial.print("\t");
            Serial.print(aaReal1.y);
            Serial.print("\t");
            Serial.println(aaReal1.z);
        #endif

        #ifdef OUTPUT_READABLE_WORLDACCEL1
            // display initial world-frame acceleration, adjusted to remove gravity
            // and rotated based on known orientation from quaternion
            mpu1.dmpGetQuaternion(&q1, fifoBuffer1);
            mpu1.dmpGetAccel(&aa1, fifoBuffer1);
            mpu1.dmpGetGravity(&gravity1, &q1);
            mpu1.dmpGetLinearAccel(&aaReal1, &aa1, &gravity1);
            mpu1.dmpGetLinearAccelInWorld(&aaWorld1, &aaReal1, &q1);
            Serial.print("aworld1\t");
            Serial.print(aaWorld1.x);
            Serial.print("\t");
            Serial.print(aaWorld1.y);
            Serial.print("\t");
            Serial.println(aaWorld1.z);
        #endif
    
        #ifdef OUTPUT_TEAPOT1
            // display quaternion values in InvenSense Teapot demo format:
            teapotPacket1[2] = fifoBuffer1[0];
            teapotPacket1[3] = fifoBuffer1[1];
            teapotPacket1[4] = fifoBuffer1[4];
            teapotPacket1[5] = fifoBuffer1[5];
            teapotPacket1[6] = fifoBuffer1[8];
            teapotPacket1[7] = fifoBuffer1[9];
            teapotPacket1[8] = fifoBuffer1[12];
            teapotPacket1[9] = fifoBuffer1[13];
            Serial.write(teapotPacket1, 14);
            teapotPacket1[11]++; // packetCount, loops at 0xFF on purpose
        #endif

        // blink LED to indicate activity
        blinkState = !blinkState;
        digitalWrite(LED_PIN, blinkState);
    }
}
}
