### ISSUE TITLE
ld.exe:Disabling relaxation: it will not work with multiple definitions

### ISSUE THREAD

**Issue by kuckyder2te** [jrowberg/i2cdevlib#92]
Hello,
I use the Lib "MPU6050" in a project. Everything works fine. 
But the MPU setup runs in the main (ino) file. The MPU data 
read from the main loop. (See MPU6050 example). 
I want the MPU6050-Lib in a separate project class 
to use.
Looks like this:
void IMUClass::init()   (from main setup)
{
    Serial.println(F("Initializing I2C devices..."));
    mpu.initialize();
etc.
}

void IMUClass::readMPU()(from main loop)
{
    mpuInterrupt = false;
    mpuIntStatus = mpu.getIntStatus();
    fifoCount = mpu.getFIFOCount();
etc.
}
If I all includes (MPU6050_9Axis_MotionApps41.h …), declarations and initializations in my class 
have defined, comes this message.
Compiling 'MPU9150_Test' for 'Arduino Mega 2560 or Mega ADK'
MPU9159Class.cpp.o:In function `MPU6050::dmpGetAccel(long_, unsigned 
char const_)'
MPU6050_9Axis_MotionApps41.h:dmpGetAccel(long_, unsigned char const_)'
MPU9150_Test.cpp.o:\MPU6050_9Axis_MotionApps41.h:636: first defined here
ld.exe:Disabling relaxation: it will not work with multiple definitions

I understand what the compiler says, but how do I disable the error?

The Libs
# include "MPU6050_9Axis_MotionApps41.h"
# include "helper_3dmath.h"
# include "I2Cdev.h"

located in the project directory. I work with VS + Visual Micro and Arduino IDE.

I'm really desperate.
Best regards
Willi

**Comment by D3Rnatch** [comment]
Hi,

Just having the same problem, did you manage to find the solution ?

Best regards,
Alex

**Comment by kuckyder2te** [comment]
Hello Alex,
I can´t solve the problem. But now I use the MPU9150lib. No Problems.
Best Regards Willi

2015-01-22 14:16 GMT+01:00 Alexandre Brand <notifications@github.com>:

**Comment by D3Rnatch** [comment]
Hi i resolved the issue adding the inline statement in .h function
description.

Best,

Alex

2015-01-22 15:09 GMT+01:00 kuckyder2te <notifications@github.com>:

> Hello Alex,
> I can´t solve the problem. But now I use the MPU9150lib. No Problems.
> Best Regards Willi
>
> 2015-01-22 14:16 GMT+01:00 Alexandre Brand <notifications@github.com>:
>
> > Hi,
> >
> > Just having the same problem, did you manage to find the solution ?
> >
> > Best regards,
> > Alex
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jrowberg/i2cdevlib/issues/92#issuecomment-71018400>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrowberg/i2cdevlib/issues/92#issuecomment-71024871>.
>



-- 
﻿[image: JEECE]Alexandre BRAND
Chef de Projet
Junior-Entreprise de l'ECE Paris
 alexandre.brand@jeece.fr
<guillaume.bignon@jeece.fr?%20&subject=[JEECE]%20Objet%20de%20votre%20mail.%20&body=Votre%20message.>

 06 78 45 98 17
[image: F]  <https://www.facebook.com/JEECE.JE>[image: T]
<https://twitter.com/JuniorJEECE>[image: G+]
<https://plus.google.com/106376338307875330368/posts>[image: L]
<http://www.linkedin.com/company/jeece>[image: V]
<http://fr.viadeo.com/fr/profile/junior.jeece>[image: Y]
<http://www.youtube.com/user/JuniorJEECE>contact@jeece.fr
<contact@jeece.fr?%20&bcc=dsi@jeece.fr%20&subject=[JEECE]%20Objet%20de%20votre%20mail.%20&body=Votre%20message.>
 | 01 45 49 19 99 | www.jeece.fr

**Comment by kuckyder2te** [comment]
Hi,
Thanks for the work.

Where you pasted the inline statement. I do not understand that. I am github
beginners.

Best Willi

2015-03-16 15:15 GMT+01:00 Alexandre Brand <notifications@github.com>:

**Comment by kuckyder2te** [comment]
I think I now understand it yet. I have to reload the library. Right?

Best Willi



2015-03-18 14:27 GMT+01:00 Wilhelm Kuckelsberg <willy.kuckelsberg@gmail.com>
:

**Comment by D3Rnatch** [comment]
hi,

Sry for reply latency, i couldn't reply efficiently without rechecking the
files (i worked on this a few weeks ago and forgot to reply). In my case i
was building a wrapper around the MPU lib and was having trouble during
compilation process (since the arduino c++ compiler sucks - due to either
it or the associated Makefile) - i can't remember the exact errors.
But after checking the MPU6050_6Axis_MotionApps20.h or
MPU6050_9Axis_MotionApps40.h, i added the "inline" statement where function
were implemented directly in the *.h file (instead of in a *.cpp); don't
ask me further explanation but it resolved my problem. You might need to
reload librairies (even thought if you modified the
/home/sketchbook/librairies/ files you would only need to restart the
arduino program).

Hope it helps ;).

Best D3Rnatch

2015-03-18 17:15 GMT+01:00 kuckyder2te <notifications@github.com>:

**Comment by kuckyder2te** [comment]
Thanks for the support. I will try this. 
Willi

**Comment by timdan-3** [comment]
I had the same problem with the Disabling Relaxation: Multiple defenitions of...

I was compiling for Arduino using WinAVR, but it turned out that switching the setting for AVR-GCC in Eclipse to the one in:
`C:\Program Files (x86)\Arduino\hardware\tools\avr\bin`
instead of 
`C:\WinAVR-20100110\utils\bin
solved the problem.

**Comment by jrowberg** [comment]
This should be fixed with the most recent commit. Finally.
